### ISSUE TITLE
didChangeAuthorization method is  calling always

### ISSUE THREAD

**Issue by maheshmobile** [Root-App/root-ios-slc-tester#1]
didChangeAuthorization method is  calling always in my code, not in your app. can you help me

**Comment by jimmy-devine** [comment]
This issue looks like a question that would be best asked on [StackOverflow](https://stackoverflow.com/questions/tagged/ios).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub issues page for bugs only.

I'll close this as this is really a question that should be asked on StackOverflow.
